site_name: New Lemon Review
site_url: https://review.youwei.xyz
site_author: 'PKU Lemonade'

theme:
  name: material
  icon:
    logo: fontawesome/regular/lemon
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.follow
    # - toc.integrate
    - navigation.top

plugins:
  - search
  - macros  
  - git-revision-date-localized

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  # Python Markdown Extensions
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - stylesheets/extra.css

nav:
  - README: README.md
  - Hardware: 
    - hardware/index.md
    - Processor Architecture: hardware/processor.md
    - Parallel and Multi-Processor Architecture: hardware/parallel.md
    - Memory Architecture: hardware/memory.md
    - Domain-Specific Accelerators: hardware/accelerators.md
    - Interconnection Networks: hardware/network.md
    - Electronic Design Automation: hardware/eda.md
    - Security and Reliability: hardware/fail.md
    - Emerging Technologies: hardware/emerging.md
    - Performance Analysis (to be deleted): hardware/perf.md
  - Software:
    - software/index.md
    - Algorithms: software/algorithm.md
    - Programming Languages: software/pl.md
    - Operating Systems: software/os.md
    - Distributed Systems: software/ds.md
    # - Computer Networks: software/network.md
    # - Database Systems: software/db.md
    # - Security: software/security.md
    - High-Performance Computing: software/hpc.md
    - Performance Analysis: software/perf.md

