site_name: New Lemon Review
site_url: https://review.youwei.xyz
site_author: 'PKU Lemonade'

theme:
  name: material
  features:
    - navigation.tracking
    - navigation.sections
    - navigation.expand

plugins:
  - search
  - macros
  - git-revision-date-localized
  - git-authors:
      show_contribution: true
      sort_authors_by: contribution
      show_line_count: true

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions

extra_css:
  - stylesheets/extra.css

nav:
  - README: index.md
  - Hardware: 
    - Processor Architecture: hardware/processor.md
    - Parallel and Multi-Processor Architecture: hardware/parallel.md
    - Memory Architecture: hardware/memory.md
    - Domain-Specific Accelerators: hardware/accelerators.md
    # - Interconnection Networks: hardware/interconnect.md
    # - Security and Reliability: hardware/security.md
    - Emerging Technologies: hardware/emerging.md
  - Software:
    - Programming Languages and Software Engineering: software/plse.md
    - Operating Systems: software/os.md
    - Runtime Systems: software/runtime.md
    # - Database Systems: software/db.md
    - High-Performance Computing: software/hpc.md
    # - Security: software/security.md

