site_name: New Lemon Review
site_url: https://review.youwei.xyz
site_author: 'PKU Lemonade'

theme:
  name: material
  features:
    - navigation.tracking
    # - navigation.sections
    - navigation.expand
    - navigation.indexes

plugins:
  - search
  - macros  
  - git-revision-date-localized

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions

extra_css:
  - stylesheets/extra.css

nav:
  - README: index.md
  - Hardware: 
    - hardware/hardware.md
    - Processor Architecture: hardware/processor.md
    - Parallel and Multi-Processor Architecture: hardware/parallel.md
    - Memory Architecture: hardware/memory.md
    - Domain-Specific Accelerators: hardware/accelerators.md
    # - Interconnection Networks: hardware/network.md
    - Security and Reliability: hardware/fail.md
    - Emerging Technologies: hardware/emerging.md
  - Software:
    - software/software.md
    - Programming Languages and Software Engineering: software/pl.md
    - Operating Systems: software/os.md
    - Runtime Systems: software/runtime.md
    # - Computer Networks: software/network.md
    # - Database Systems: software/db.md
    - High-Performance Computing: software/hpc.md
    # - Security: software/security.md

